-- Review Cycle Dashboard schema bootstrap
CREATE SCHEMA IF NOT EXISTS REVIEW_CYCLE;

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.USERS (
    USER_ID NUMBER AUTOINCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255),
    ROLE VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.PROJECTS (
    PROJECT_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    BASE_SCHEMA VARCHAR(255),
    ELVIS_DATABASE VARCHAR(255),
    ELVIS_TABLE VARCHAR(255),
    MAIN_DATABASE VARCHAR(255),
    MAIN_TABLE VARCHAR(255),
    DETAILS_FILE_NAME VARCHAR(512),
    CR_FILE_NAME VARCHAR(512),
    KINGELVIS_FILE_NAME VARCHAR(512),
    ELVIS_PROJECT_NAME VARCHAR(255),
    PIPELINE_PROJECT_CODE VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    SYNCED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.RECORDS (
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    BATCH_ID VARCHAR(64),
    INGESTED_AT TIMESTAMP_NTZ,
    IS_NEW BOOLEAN DEFAULT FALSE,
    FINAL_USAGE VARCHAR(64),
    FINAL_REVIEWER VARCHAR(255),
    ROUTE_SURVEYED_CODE VARCHAR(255),
    INTERV_INIT VARCHAR(64),
    ELVIS_STATUS VARCHAR(255),
    SUPERVISOR_COMMENT VARCHAR(4000),
    FIRST_CLEANER VARCHAR(255),
    REASON_FOR_REMOVAL VARCHAR(2000),
    RECORD_PAYLOAD VARIANT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(255),
    PRIMARY KEY (PROJECT_NAME, RECORD_ID)
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.COMBINED_CHECKS (
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    BATCH_ID VARCHAR(64),
    TRADITIONAL_CHECK NUMBER DEFAULT 0,
    OD_DISTANCE_CHECK NUMBER DEFAULT 0,
    TRANSFER_DISTANCE_CHECK NUMBER DEFAULT 0,
    STOPLISTVALIDATION_CHECK NUMBER DEFAULT 0,
    TWO_X_REVIEW_CHECK NUMBER DEFAULT 0,
    SUM_ALL_CHECKS NUMBER DEFAULT 0,
    ADMIN_APPROVED BOOLEAN DEFAULT FALSE,
    ESCALATED BOOLEAN DEFAULT FALSE,
    TWO_X_REVIEWED_BY VARCHAR(255),
    TWO_X_REVIEWED_FLAG VARCHAR(255),
    CHECK_PAYLOAD VARIANT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROJECT_NAME, RECORD_ID)
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.DECISION_HISTORY (
    HISTORY_ID NUMBER AUTOINCREMENT,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    FIELD_NAME VARCHAR(255) NOT NULL,
    OLD_VALUE VARCHAR(4000),
    NEW_VALUE VARCHAR(4000),
    ACTION VARCHAR(255),
    ACTOR VARCHAR(255),
    ACTOR_ROLE VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.ASSIGNMENTS (
    ASSIGNMENT_ID NUMBER AUTOINCREMENT,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    ASSIGNED_TO VARCHAR(255),
    TEAM VARCHAR(64),
    STATUS VARCHAR(64) DEFAULT 'assigned',
    PRIORITY NUMBER DEFAULT 100,
    ASSIGNED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DEFER_UNTIL TIMESTAMP_NTZ,
    NOTES VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.REVIEWER_STATS (
    PROJECT_NAME VARCHAR(255) NOT NULL,
    STAT_TYPE VARCHAR(128) NOT NULL,
    STAT_KEY VARCHAR(512) NOT NULL,
    METRIC_NAME VARCHAR(255) NOT NULL,
    METRIC_VALUE FLOAT,
    METRIC_TEXT VARCHAR(4000),
    BATCH_ID VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.SYNC_STATE (
    PROJECT_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    LAST_PULL_TS TIMESTAMP_NTZ,
    LAST_OD_SYNC_SEEN TIMESTAMP_NTZ,
    LAST_KINGELVIS_EXPORT_TS TIMESTAMP_NTZ,
    LAST_PIPELINE_STATUS VARCHAR(64),
    LAST_PIPELINE_MESSAGE VARCHAR(4000),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.ORIGINAL_RECORDS (
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    RECORD_PAYLOAD VARIANT,
    CAPTURED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROJECT_NAME, RECORD_ID)
);
