-- Review Cycle Dashboard schema additions (idempotent, additive only).
-- Notification Center, Data Quality Alerts, and Demographic Review results.

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.NOTIFICATIONS (
    NOTIFICATION_ID NUMBER AUTOINCREMENT,
    RECIPIENT VARCHAR(255) NOT NULL,
    NTYPE VARCHAR(64) NOT NULL,
    MESSAGE VARCHAR(4000),
    PROJECT_NAME VARCHAR(255),
    RECORD_ID VARCHAR(64),
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.QUALITY_ALERTS (
    ALERT_ID NUMBER AUTOINCREMENT,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    ALERT_TYPE VARCHAR(64) NOT NULL,
    SUBJECT VARCHAR(512),
    METRIC_VALUE FLOAT,
    THRESHOLD FLOAT,
    SEVERITY VARCHAR(32),
    MESSAGE VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEW_CYCLE.DEMOGRAPHIC_CHECKS (
    PROJECT_NAME VARCHAR(255) NOT NULL,
    RECORD_ID VARCHAR(64) NOT NULL,
    CHECK_TYPE VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32),
    DETAIL VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROJECT_NAME, RECORD_ID, CHECK_TYPE)
);
