"""Shared presentation helpers for the Review Cycle Dashboard."""

from views.ui.buttons import ghost_button, primary_button, secondary_button
from views.ui.components import (
    action_row,
    app_topbar,
    auth_card,
    auth_hero,
    auth_meta,
    badge,
    count_badge,
    dashboard_card,
    drill_section_label,
    empty_state,
    filter_panel,
    form_field_label,
    info_strip,
    metric_card,
    metric_row,
    page_actions,
    page_header,
    page_toolbar,
    workspace_toolbar,
    section,
    section_header,
    section_header_compact,
    section_title,
    set_header_context,
    sidebar_account_label,
    sidebar_brand,
    sidebar_nav_label,
    stats_bar,
    table_section_chrome,
    table_section_footer,
    user_card,
)
from views.ui.styles import inject_global_css

__all__ = [
    "action_row",
    "app_topbar",
    "auth_card",
    "auth_hero",
    "auth_meta",
    "badge",
    "count_badge",
    "dashboard_card",
    "empty_state",
    "filter_panel",
    "ghost_button",
    "info_strip",
    "inject_global_css",
    "metric_card",
    "metric_row",
    "page_actions",
    "page_header",
    "page_toolbar",
    "workspace_toolbar",
    "primary_button",
    "secondary_button",
    "section",
    "section_header",
    "section_header_compact",
    "section_title",
    "set_header_context",
    "sidebar_account_label",
    "sidebar_brand",
    "sidebar_nav_label",
    "stats_bar",
    "table_section_chrome",
    "table_section_footer",
    "drill_section_label",
    "form_field_label",
    "user_card",
]
